### ISSUE TITLE
Create 3D print top and bottom pieces 

### ISSUE THREAD

**Issue by nooges** [keebio/quefrency-case#1]

**Comment by szaghi** [comment]
My friend Luca has create the top and bottom plates design (for the 65% version), you can find them here

https://www.thingiverse.com/thing:3644626

**Comment by danseely** [comment]
@nooges does this refer to entire case top & bottom parts? I'd love files for a hi-profile top lip, not sure if that would be included in what you were thinking here, or if you'd rather I make another issue just for that 😀
