### ISSUE TITLE
Quefrency Rev 2 middle layer incompatible with instructions

### ISSUE THREAD

**Issue by FThompson** [keebio/quefrency-case#10]
I'm building a Quefrency Rev 2, and I followed the instructions in the [build guide](https://docs.keeb.io/docs/quefrency-rev2-sinc-build-guide/#assemble-case). This guide says to attach the standoffs to the top plate and then slide the middle layer over the standoffs before attaching the bottom plate.

Issue: The thin section of the middle layer (where the ports fit) collide with the ports themselves when attempting this step. The thin section appears to fit between the ports and the top plate. However, they block the middle layer from sliding over the top. It appears that this middle layer would fit only if attached to the top plate before the PCB.

It seems that the build guide has the right idea to add the case as one of the later steps (nobody wants to try and solder around a middle layer). However, the models aren't compatible with these instructions.

The easiest fix would be to remove the thin sections around each port on the model.

**Comment by nooges** [comment]
For the 3D printed layer, what you have to do is unscrew the standoffs from the switch plate, insert the standoffs into the middle layer, then fit the switch plate/PCB through the middle layer from the side. Then screw in the standoffs to the switch plate.
