### ISSUE TITLE
Rev.4 missing 60% right layout

### ISSUE THREAD

**Issue by miromannino** [keebio/quefrency-case#13]
Hello, I am wondering where I can find the plate files for the 60% rev4 right side. 
Isn't possible to have a 60% for the v4?
Thanks in advance for the reply

**Comment by nooges** [comment]
Plate files for Rev. 4 are the same as Rev. 2

**Comment by miromannino** [comment]
The only 60% one I can find for the switches plate is: [switch-plate-3mm-right.dxf ](https://github.com/keebio/quefrency-case/blob/master/rev2/3mm%20Plates/switch-plate-3mm-right.dxf)

But this has a long hole in the bottom part. According to this Keebio's video instead https://www.youtube.com/watch?v=ONEaWsojIn0&t=80s it seems there is a new plate that doesn't have that long gap at the bottom.

**Comment by nooges** [comment]
You want this file: https://github.com/keebio/quefrency-case/blob/master/rev2/switch-plate-right.dxf

**Comment by miromannino** [comment]
Uhm I saw that but like the video said, at the bottom there is a long opened part that would make show the pcb on rev4.

Attached the screenshots to show:

![rev2-60-vs-rev4-65](https://user-images.githubusercontent.com/160922/172448049-df987cef-2bd3-4895-bc0d-6b8513012db8.png)

Instead a 60% for rev4 I guess should be something like this? (red parts are the ones taken from the rev4 drawing)

![Screen Shot 2022-06-08 at 10 47 44 ](https://user-images.githubusercontent.com/160922/172550634-71feb9f5-0d47-49f8-bdaa-197eec987d35.png)

I just did in Illustrator, I have no idea how to change these files.

**Comment by miromannino** [comment]
This is the problem I am talking about. I have a rev4 pcb, but the plates are from the 60% version 2, and the pcb is visible:
    
![Screen Shot 2022-06-10 at 18 15 43 ](https://user-images.githubusercontent.com/160922/173085394-5c79e1c2-5f35-480c-8b50-ddca68362da8.png)

Thank you in advance

**Comment by nooges** [comment]
Ah okay, I'll get a new file posted up for it.

**Comment by nooges** [comment]
Okay, I've added it in now: https://github.com/keebio/quefrency-case/blob/master/rev4/switch-plate-rev4-right-60.dxf

**Comment by miromannino** [comment]
Perfect thank you so much! 😀
