### ISSUE TITLE
too much tight tolerance for 3D print

### ISSUE THREAD

**Issue by szaghi** [keebio/quefrency-case#2]
Hi @nooges 

thank you very much for sharing your work.

I have 3D printed your middle layers and they are great! However, the *tolerance" of the holes for usb and jack cables are too much "tight": they fit perfectly, but they must be installed before the pro micro are soldered and cannot be removed without desoldering. I have slightly modified your design allowing some more tolerance for that holes and now the middle layers can be installed and uninstalled effortless (I have attached some pictures of my current design). 

Do you mind to publish your design and my modifications on thingiverse? There are much more 3D makers than on github.

![scaled-IMG_20190322_094931](https://user-images.githubusercontent.com/1661942/54817296-dbec1b80-4c96-11e9-89ec-291213d6b140.jpg)
![scaled-IMG_20190322_095006](https://user-images.githubusercontent.com/1661942/54817297-dbec1b80-4c96-11e9-9b14-d0f69d0a8ac5.jpg)

**Comment by donkalar** [comment]
If you do end up posting your mods on thingiverse, be sure to also post a link!

**Comment by szaghi** [comment]
@donkalar Hi, I do not have yet posted anything just because I have not obtained the permission by @nooges , can I?

**Comment by nooges** [comment]
Yeah go ahead.

**Comment by szaghi** [comment]
I have published our efforts: I have cited you and this original source, let me know if it is fine or if I have to amend it.  

https://www.thingiverse.com/thing:3644626

**Comment by Riven-Spell** [comment]
@szaghi do you plan to make a outer layer for the left hand macro version?

**Comment by szaghi** [comment]
Hi @Virepri

I probably will do within other cases for the standard 65%. The problem is that I saw the left hand macro version (Reddit), but I am not able to find where to buy a PCB. 

Do you have it? Where can I buy the left hand macro PCB?

Cheers

**Comment by szaghi** [comment]
Forgive me, I have just see that the macro version is available on the keebio store, I will buy it and I'll try to build a case also for it, I do not know when... I have a lot of ongoing projects now.
