### ISSUE TITLE
Rev 2 Mid Right 65 has intersecting faces

### ISSUE THREAD

**Issue by brandon099** [keebio/quefrency-case#6]
When trying to have these printed, looks like there are three intersecting faces on top of the USB-C port opening. Mid Left STL looks good.

![image](https://user-images.githubusercontent.com/1628223/88864179-d6271400-d1c1-11ea-8abe-954a531e1487.png)
![image](https://user-images.githubusercontent.com/1628223/88864237-f35be280-d1c1-11ea-9e9c-443543b3f8fb.png)

**Comment by nooges** [comment]
I'll have a more formal version of the mids soon with more form-fitting cutouts for the two jacks to replace the current STLs I posted up as a quick and dirty version.
